alias cdsdk='cd $HOME/dev/repos/fusion-wowool-sdk'
alias cdsdknative='cd $HOME/dev/repos/fusion-wowool-sdk/comp-wowool-sdk-native-py-cpp'
alias cdportal='cd $HOME/dev/repos/fusion-wowool-portal'
alias cdbreach='cd $HOME/dev/repos/fusion-breach-extractor'
alias cdwowooldocs='cd $HOME/dev/repos/wowool-docs'
alias conf-zsh-eot='e $HOME/dev/repos/setup/zsh/profile/eot.zsh'
alias eot-mount-breachserver='sudo mkdir -p /mnt/eot-breachserver && sudo sshfs -o debug,allow_other,IdentityFile=/home/djamelg/.ssh/id_rsa djgr@35.170.58.49:/mnt/efs/ /mnt/eot-breachserver'

function eot-rebuild-tir {
    unset EOT_KEY
    unset EOT_ROOT

    cdsdk
    senv
    inv pull
    
    cd tir
    inv glf
    inv cpp.config --release
    inv cpp.build/release

    cd ..

    cd stage/lxware
    #rm *-entity.dom

    cd ../..

    cd lingware
    inv lid.build
    inv lxcommon.build
    inv english.build-entity
    inv english.build-entity-extended
}

function eot-create-pip-conf() {
    echo "# Do not edit this file directly
# Generated by setup/zsh/profile/eot.zsh:eot-pip-conf
[global]
trusted-host = https://pypi.org/simple
               https://$EOT_NEXUS_USERNAME:$EOT_NEXUS_PASSWORD@nexus.eyeonid.com
index = https://$EOT_NEXUS_USERNAME:$EOT_NEXUS_PASSWORD@nexus.eyeonid.com/repository/eyeontext-pypi/pypi
extra-index-url = https://$EOT_NEXUS_USERNAME:$EOT_NEXUS_PASSWORD@nexus.eyeonid.com/repository/eyeontext-pypi/simple

[list]
format=columns
" > env/pip.conf
}

function eot-menv() {
    python3 -m venv env
    source env/bin/activate
    pip3 config set global.extra-index-url https://${EOT_NEXUS_USERNAME}:${EOT_NEXUS_PASSWORD_ENCODED}@repo.eyeontext.com/repository/eyeontext-pypi/simple --site
    menv
}
function eot-menv-release() {
    eot-menv
    senv
    if [ -f "install_requires.txt" ]; then
        pip3 install -r install_requires.txt
    fi
    if [ -f "install_requires_eot.txt" ]; then
        pip3 install -r install_requires_eot.txt
    fi
    if [ -f "dev_requires.txt" ]; then
        pip3 install -r dev_requires.txt
    fi
    if [ -f "dev_requires_eot.txt" ]; then
        pip3 install -r dev_requires_eot.txt
    fi
}
function eot-menv-dev() {
    echo "Installing development environment"
    eot-menv
    senv
    if [ -f "install_requires.txt" ]; then
        echo "Installing install_requires.txt"
        pip3 install -r install_requires.txt
    else
        echo "Skipping install_requires.txt"
    fi
    if [ -f "install_requires_eot.txt" ]; then
        echo "Installing install_requires_eot (pre-releases).txt"
        pip3 install --pre -r install_requires_eot.txt
    else
        echo "Skipping install_requires_eot.txt"
    fi
    if [ -f "dev_requires.txt" ]; then
        echo "Installing dev_requires.txt"
        pip3 install -r dev_requires.txt
    else
        echo "Skipping dev_requires.txt"
    fi
    if [ -f "dev_requires_eot.txt" ]; then
        echo "Installing dev_requires_eot (pre-releases).txt"
        pip3 install --pre -r dev_requires_eot.txt
    else
        echo "Skipping dev_requires_eot.txt"
    fi
}
function eot-ienv() {
    senv
    echo "Installing pre-releases listed in install_requires_eot.txt"
    pip3 install --pre -r install_requires_eot.txt
    echo "Install stable releases listed in install_requires.txt"
    pip3 install -r install_requires.txt
    echo "Installing pre-releases listed in dev_requires_eot.txt"
    pip3 install --pre -r dev_requires_eot.txt
    echo "Install stable releases listed in dev_requires.txt"
    pip3 install -r dev_requires.txt
    echo "Installing pre-releases listed in build_requires_eot.txt"
    pip3 install --pre -r build_requires_eot.txt
    echo "Install stable releases listed in build_requires.txt"
    pip3 install -r build_requires.txt
}

alias conf-eot='e ~/dev/repos/setup/zsh/profile/eot.zsh'
alias eot-devserver='ssh -vv -i ${HOME}/dev/repos/docs/docs-eot/data/debian-buildserver.pem dev@3.64.83.152'
alias eot-devserver-root='ssh -i ${HOME}/dev/repos/docs/docs-eot/data/debian-buildserver.pem ubuntu@3.64.83.152'
alias eot-breachserver='ssh djgr@35.170.58.49'
