alias cdfusion='cdrepos; cd fusion'

function eot-tir-rebuild {
    unset EOT_KEY
    unset EOT_ROOT

    cdrepos
    cd fusion-wowool-sdk
    senv
    inv pull
    
    cd tir
    inv glf
    inv cpp.config --release
    inv cpp.build/release

    cd ..

    cd stage/lxware
    rm *-entity.dom

    cd ../..

    cd lingware
    inv lid.build
    inv lxcommon.build
    inv english.build-entity
    inv english.build-entity-extended

    
    cdfusion
    export EOT_KEY=EOTDEV 
    export EOT_ROOT=~/dev/repos/fusion-wowool-sdk/stage
    senv
    inv pull
    inv comp-wowool-sdk-native-py-cpp.clean
    inv comp-wowool-sdk-native-py-cpp.build
    inv ut
}

function eot-pip-conf {
    echo "# Do not edit this file directly
# Generated by setup/zsh/profile/eot.zsh:eot-pip-conf
[global]
trusted-host = https://pypi.org/simple
               https://nexus.eyeonid.com
index = https://nexus.eyeonid.com/repository/eyeontext-pypi/pypi
extra-index-url = https://nexus.eyeonid.com/repository/eyeontext-pypi/simple

[list]
format=columns
" > env/pip.conf
}
